apps/discord-bot/src/domains/consent.test.ts
apps/discord-bot/src/domains/consent.ts
apps/discord-bot/src/listeners/events/forum-post-guidelines-consent.test.ts
apps/discord-bot/src/listeners/events/forum-post-guidelines-consent.ts
apps/discord-bot/tsconfig.json
apps/discord-bot/tsup.config.ts
packages/api/src/router/context.ts
packages/api/src/router/trpc.ts

Forum Post Guidelines Consent

---

.devcontainer/ui/devcontainer.json
answeroverflow.code-workspace

Adds devcontainer file for UI work only
Closes #194 

(feat): add ui dev container

---

README.md

Fixes #210  (issue)
Update of README
N/A

tweak(readme): subtitle

---

.github/ISSUE_TEMPLATE/component.yml
README.md

Fixes #206 (issue)
Issue template update
N/A
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have made corresponding changes to the documentation
- [ x ] I have added tests that prove my fix is effective or that my feature works 
- [ x ] I have updated .env.example if I added a new environment variable
- [ x ] My PR title follows the [semantic commits](https://www.conventionalcommits.org/en/v1.0.0/) style

Component-issue-template

---

.devcontainer/devcontainer.json
.devcontainer/ui/devcontainer.json
answeroverflow.code-workspace
apps/docs/.eslintrc.js
apps/docs/README.md
apps/docs/next-env.d.ts
apps/docs/next.config.mjs
apps/docs/package.json
apps/docs/postcss.config.cjs
apps/docs/src/pages/_app.tsx
apps/docs/src/pages/_document.tsx
apps/docs/src/pages/_meta.json
apps/docs/src/pages/api/auth/[...nextauth].ts
apps/docs/src/pages/api/trpc/[trpc].ts
apps/docs/src/pages/index.mdx
apps/docs/src/styles/globals.css
apps/docs/tailwind.config.cjs
apps/docs/theme.config.tsx
apps/docs/tsconfig.json
package.json
yarn.lock

Adds a documentation site that users Nextra
Closes #162 

[feat]: docs site

---

CONTRIBUTING.md
answeroverflow.code-workspace
apps/discord-bot/src/commands/settings/open-manage-account-menu.tsx
apps/discord-bot/src/commands/settings/open-server-settings-menu.tsx
apps/discord-bot/src/components/instructions-container.tsx
apps/discord-bot/src/components/instructions.tsx
apps/discord-bot/src/components/manage-account-menu.test.tsx
apps/discord-bot/src/components/manage-account-menu.tsx
apps/discord-bot/src/components/server-settings-menu.test.tsx
apps/discord-bot/src/components/server-settings-menu.tsx
apps/discord-bot/src/components/toggle-button.tsx
apps/discord-bot/src/domains/manage-account.ts
apps/discord-bot/src/domains/server-settings.ts
apps/discord-bot/test/reacord-utils.tsx
apps/discord-bot/tsconfig.json
packages/api/src/router/server/server.test.ts
packages/api/src/router/server/server.ts
packages/api/src/router/user-server-settings/user-server-settings.ts
packages/api/src/utils/permissions.ts
packages/config/tsconfig/base.json
packages/config/tsconfig/nextjs.json
packages/db-mock/index.ts
packages/db/src/server.ts
packages/ui/tsconfig.json

Closing #4 
- Merges channel settings state into one state object to fix double update bugs
- Server Settings Menu & Slash Command

(feat): server settings menu

---

CONTRIBUTING.md

Add a little note in the contributing guidelines about installing docker compose for containers on Linux.

docs: add note about docker compose for containers on linux

---

DESIGN_GUIDELINES.md

Updates design guidelines
Fixes #205 (issue)
Design guidelines change
N/A

tweak(docs): design guidelines

---

DESIGN_GUIDELINES.md
packages/config/tailwind/index.js

tweak(config/tailwind): colors

---

DESIGN_GUIDELINES.md

fix(design_guidelines): error in white hex code

---

answeroverflow.code-workspace
apps/discord-bot/src/domains/indexing.ts
apps/discord-bot/src/domains/send-mark-solution-instructions.test.ts
apps/discord-bot/src/domains/send-mark-solution-instructions.ts
apps/discord-bot/src/listeners/events/send-mark-solution-instructions-listener.test.ts
apps/discord-bot/src/listeners/events/send-mark-solution-instructions-listener.ts
apps/discord-bot/src/listeners/parity/guild-parity.ts
packages/db/src/channel.test.ts
packages/db/src/channel.ts
packages/discordjs-mock/src/channel-mock.ts
packages/discordjs-mock/src/interaction-mock.ts
packages/discordjs-mock/src/message-mock.ts

- Fix overriding settings when syncing guilds
- Send mark solution directions in new threads

feat(bot): automatically send mark solution instructions

---

apps/discord-bot/src/commands/settings/consent-command.ts
apps/discord-bot/src/commands/settings/open-channel-settings-menu.tsx
apps/discord-bot/src/commands/settings/open-manage-account-menu.tsx
apps/discord-bot/src/commands/settings/open-server-settings-menu.tsx
apps/discord-bot/src/components/settings/channel-settings-menu.test.tsx
apps/discord-bot/src/components/settings/channel-settings-menu.tsx
apps/discord-bot/src/components/settings/manage-account-menu.tsx
apps/discord-bot/src/domains/manage-account.test.ts
apps/discord-bot/src/domains/manage-account.ts
apps/discord-bot/src/domains/mark-solution.test.ts
apps/discord-bot/src/domains/mark-solution.ts
apps/discord-bot/src/domains/send-mark-solution-instructions.test.ts
apps/discord-bot/src/interaction-handlers/consent-button.test.ts
apps/discord-bot/src/interaction-handlers/consent-button.ts
apps/discord-bot/src/utils/trpc.ts
packages/api/src/router/user-server-settings/types.ts
packages/constants/index.ts

Support consenting via buttons
Closing #10 
Channel Settings Menu:
Consent button interaction handler:

feat(bot): consent buttons

---

packages/ui/src/components/primitives/Paragraph.tsx

fix(ui): paragraph padding style

---

packages/api/src/router/server/server.ts
packages/db-mock/index.ts
packages/db/src/server.test.ts
packages/db/src/server.ts
packages/prisma-types/prisma/schema.prisma
packages/prisma-types/src/default.ts
packages/prisma-types/src/zod-schemas.ts
packages/ui/src/components/index.ts
packages/utils/src/id.ts

feat(web): vanity urls

---

apps/discord-bot/package.json
apps/docs/theme.config.tsx
apps/nextjs/src/pages/c/[communityId]/[channelId]/sitemap.xml.ts
apps/nextjs/src/pages/c/[communityId]/sitemap.xml.ts
apps/nextjs/src/pages/robots.txt
apps/nextjs/src/pages/sitemap.xml.ts
apps/nextjs/src/utils/sitemap.ts
package.json
packages/api/package.json
packages/db/src/channel.ts
packages/db/src/message.ts
packages/db/src/server.ts
packages/discordjs-mock/package.json
packages/discordjs-mock/src/channel-mock.ts
packages/discordjs-mock/src/message-mock.ts
packages/discordjs-mock/src/to-api-data.ts
packages/discordjs-utils/package.json
packages/elastic-types/package.json
packages/elastic-types/src/elastic.ts
packages/ui/src/components/ServerInvite.tsx
packages/ui/src/components/primitives/Navbar.tsx
packages/ui/src/utils/decorators.tsx
packages/ui/src/utils/hooks.ts
yarn.lock

Adds a sitemap that generates in the following format:
All servers
-> Server, all channels
-> All questions in channel

feat(web): sitemap

---

packages/ui/src/components/pages/home/AboutArea.tsx

For now, I've removed drop shadows on the features section within the home page
No github issue needed
N/A

fix(ui/home): drop shadow render bug

---

apps/discord-bot/src/commands/settings/open-channel-settings-menu.tsx
apps/discord-bot/src/components/primitives/support.tsx
apps/discord-bot/src/components/settings/channel-settings-menu.test.tsx
apps/discord-bot/src/components/settings/channel-settings-menu.tsx
packages/constants/src/discord.ts
packages/db/src/message.ts
packages/elastic-types/src/elastic.ts

Adds a button to jump to the last indexed message

feat(bot): add jump to last indexed message button

---

answeroverflow.code-workspace
apps/discord-bot/src/commands/settings/consent-command.ts
apps/discord-bot/src/commands/settings/open-channel-settings-menu.tsx
apps/discord-bot/src/commands/settings/open-manage-account-menu.tsx
apps/discord-bot/src/commands/settings/open-server-settings-menu.tsx
apps/discord-bot/src/components/settings/channel-settings-menu.tsx
apps/discord-bot/src/components/settings/manage-account-menu.tsx
apps/discord-bot/src/domains/dismiss-button.test.ts
apps/discord-bot/src/domains/dismiss-button.ts
apps/discord-bot/src/domains/send-mark-solution-instructions.ts
apps/discord-bot/src/interaction-handlers/consent-button.ts
apps/discord-bot/src/interaction-handlers/dismiss-button-handler.ts
apps/discord-bot/src/listeners/commands/command-failure.ts
apps/discord-bot/src/utils/trpc.ts

Adds a dismiss button on the send mark solution instructions message
Closing #157 

feat(bot): dismiss button

---

packages/analytics/src/analytics.ts
turbo.json

fix(dev env): speed up slow tests

---

SECURITY.md

fix: security.md spelling error

---

apps/discord-bot/src/components/settings/manage-account-menu.tsx
apps/discord-bot/src/components/settings/server-settings-menu.test.tsx
apps/discord-bot/src/components/settings/server-settings-menu.tsx
apps/discord-bot/src/domains/server-settings.ts
packages/analytics/.eslintrc.js
packages/api/src/router/messages/messages.ts
packages/api/src/router/server/server.test.ts
packages/api/src/router/server/server.ts
packages/constants/src/discord.ts
packages/db/src/message.test.ts
packages/db/src/message.ts
packages/db/src/pages.ts
packages/db/src/server.test.ts
packages/prisma-types/src/server-schema.ts
packages/ui/test/props.ts

feat(bot): option to consider all messages as public

---

apps/discord-bot/src/components/settings/server-settings-menu.test.tsx
apps/discord-bot/src/components/settings/server-settings-menu.tsx
apps/discord-bot/src/domains/server-settings.ts
apps/discord-bot/src/listeners/events/on-question-ask.ts
packages/api/src/router/server/server.test.ts
packages/api/src/router/server/server.ts
packages/api/src/router/users/accounts/types.ts
packages/constants/src/discord.ts
packages/db/package.json
packages/db/src/message.test.ts
packages/db/src/message.ts
packages/db/src/utils/anonymization.ts
packages/prisma-types/src/discord-account-schema.ts
packages/prisma-types/src/server-schema.ts
packages/ui/test/props.ts
pnpm-lock.yaml

feat(bot): anonymize messages

---

apps/discord-bot/src/domains/indexing.ts
packages/db/src/message.ts
packages/elastic-types/src/elastic.test.ts
packages/elastic-types/src/elastic.ts
packages/ui/src/components/pages/home/HeroArea.tsx

fix(bot): speed up indexing

---

CONTRIBUTING.md
apps/discord-bot/README.md
apps/discord-bot/src/domains/mark-solution.ts
apps/discord-bot/src/listeners/events/on-question-ask.ts
apps/docs/src/pages/index.mdx
packages/api/src/router/user-server-settings/user-server-settings.test.ts
packages/api/src/router/users/accounts/discord-account.test.ts
packages/api/test/utils.test.ts
packages/api/test/utils.ts
packages/auth/src/adapter.ts
packages/config/eslint-config-custom/next.js
packages/db/src/channel.test.ts
packages/db/src/message.test.ts
packages/db/src/server.test.ts
packages/discordjs-mock/src/channel-mock.test.ts
packages/discordjs-mock/src/interaction-mock.test.ts
packages/discordjs-mock/src/user-mock.test.ts
packages/ui/src/components/pages/Pricing.tsx
packages/ui/src/components/pages/onboarding/OnboardingPages.tsx
packages/utils/src/id.ts

This fixes some typos. What a cool bot and codebase! Lmk if I need to make any edits.
N/A

docs: fix typos

---

packages/ui/src/components/pages/CommunityPage.tsx
packages/ui/src/components/primitives/server-invite.tsx

Fixes channel sidebar styling
Fixes N/A (issue)
N/A

tweak,fix(ui/ChannelSidebar): styling

---

package.json
packages/ui/src/components/pages/CommunityPage.tsx
packages/ui/src/components/primitives/server-invite.tsx

- tweak,fix(ui/ChannelSidebar): styling
- fix(ui/ChannelSidebar): styling fix 2
- tweak(packageJson): add lite dev options

improve channel sidebar styling

---

packages/ui/src/components/primitives/message/Embed.tsx

- tweak,fix(ui/Embed): improve styling for links, make title smaller
Improves styling for link embeds
Fixes N/A (issue)
N/A

tweak,fix(ui/Embed): improve styling"

---

packages/ui/src/components/primitives/message/attachments.tsx

- feat(ui/message): video attachments
Adds support for video attachments, refactors attachment regex system
Fixes N/A (issue)
N/A

feat(ui/message): support for video attachments, refactor attachment regex system"

---

apps/main-site/src/app/(main-site)/(core)/search/page.tsx
apps/main-site/src/app/[domain]/(core)/search/page.tsx

- fix(site/searchPage): optimise, don't fetch on initial load
Fixes /search so there is no fetch if no query is present
Fixes N/A (issue)
No

fix(site/searchPage): optimise

---

packages/ui/src/message/Embed.tsx

- fix(ui/Embed): embed width fit -> auto - edge case when image width is unset/404
N/A
Fixes [discord bug report](https://discord.com/channels/952724385238761475/1212090780018147431) (issue)
N/A

fix(ui/embed): embed width image edge case

---

LICENSE.md

Hey @RhysSullivan! 👋 I'm getting ready to [submit FSL to SPDX](https://github.com/getsentry/fsl.software/issues/21) and am reviewing existing adoption as part of that. Would you be up for upgrading to FSL 1.1? It has the same basic intent as 1.0 but clarifies a few things. Here are [the details](https://github.com/getsentry/fsl.software/issues/23).
License upgrade.
I copied and pasted from [fsl.software](https://fsl.software/), should be good.

Upgrade FSL to 1.1

---

apps/main-site/src/app/(main-site)/(home)/layout.tsx

fix home styling

---

packages/ui/src/navbar/index.tsx

fix(ui/navbar): search icon alignment
